<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.0
 */

/**
 * Database `shiny_pokemon`
 */

/* `shiny_pokemon`.`color` */
$color = array(
  array('id' => '5','color' => 'Black'),
  array('id' => '2','color' => 'Blue'),
  array('id' => '6','color' => 'Brown'),
  array('id' => '8','color' => 'Gray'),
  array('id' => '4','color' => 'Green'),
  array('id' => '12','color' => 'Orange'),
  array('id' => '10','color' => 'Pink'),
  array('id' => '7','color' => 'Purple'),
  array('id' => '1','color' => 'Red'),
  array('id' => '14','color' => 'Slight Change'),
  array('id' => '13','color' => 'Tan'),
  array('id' => '11','color' => 'Teal'),
  array('id' => '9','color' => 'White'),
  array('id' => '3','color' => 'Yellow')
);

/* `shiny_pokemon`.`pokemon` */
$pokemon = array(
  array('id' => '1','pokemon_name' => 'Sprigatito','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '4','accent_color' => '7','sprites' => '"Exported Crops\\1_SPRIGATITO.png"'),
  array('id' => '2','pokemon_name' => 'Floragato','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '4','accent_color' => '7','sprites' => '"Exported Crops\\2_FLORAGATO.png"'),
  array('id' => '3','pokemon_name' => 'Meowscarada','pokemon_type1' => '4','pokemon_type2' => '17','main_color' => '4','accent_color' => '7','sprites' => '"Exported Crops\\3_MEOWSCARADA.png"'),
  array('id' => '4','pokemon_name' => 'Fuecoco','pokemon_type1' => '2','pokemon_type2' => '0','main_color' => '10','accent_color' => '12','sprites' => '"Exported Crops\\4_FUECOCO.png"'),
  array('id' => '5','pokemon_name' => 'Crocalor','pokemon_type1' => '2','pokemon_type2' => '0','main_color' => '10','accent_color' => '12','sprites' => '"Exported Crops\\5_CROCALOR.png"'),
  array('id' => '6','pokemon_name' => 'Skeledirge','pokemon_type1' => '2','pokemon_type2' => '14','main_color' => '10','accent_color' => '12','sprites' => '"Exported Crops\\6_SKELEDIRGE.png"'),
  array('id' => '7','pokemon_name' => 'Quaxly','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\7_QUAXLY.png"'),
  array('id' => '8','pokemon_name' => 'Quaxwell','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '11','accent_color' => '0','sprites' => '"Exported Crops\\8_QUAXWELL.png"'),
  array('id' => '9','pokemon_name' => 'Quaquaval','pokemon_type1' => '3','pokemon_type2' => '6','main_color' => '7','accent_color' => '2','sprites' => '"Exported Crops\\9_QUAQUAVAL.png"'),
  array('id' => '10','pokemon_name' => 'Lechonk','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\10_LECHONK"'),
  array('id' => '11','pokemon_name' => 'Oinkologne','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\11_OINKOLOGNE.png"'),
  array('id' => '12','pokemon_name' => 'Tarountula','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '1','accent_color' => '5','sprites' => '"Exported Crops\\12_TAROUNTULA.png"'),
  array('id' => '13','pokemon_name' => 'Spidops','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '1','accent_color' => '5','sprites' => '"Exported Crops\\13_SPIDOPS.png"'),
  array('id' => '14','pokemon_name' => 'Nymble','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '3','accent_color' => '9','sprites' => '"Exported Crops\\14_NYMBLE.png"'),
  array('id' => '15','pokemon_name' => 'Lokix','pokemon_type1' => '13','pokemon_type2' => '17','main_color' => '6','accent_color' => '3','sprites' => '"Exported Crops\\15_LOKIX.png"'),
  array('id' => '16','pokemon_name' => 'Hoppip','pokemon_type1' => '4','pokemon_type2' => '5','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\16_HOPPIP.png"'),
  array('id' => '17','pokemon_name' => 'Skiploom','pokemon_type1' => '4','pokemon_type2' => '5','main_color' => '10','accent_color' => '3','sprites' => '"Exported Crops\\17_SKIPLOOM.png"'),
  array('id' => '18','pokemon_name' => 'Jumpluff','pokemon_type1' => '4','pokemon_type2' => '5','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\18_JUMPLUFF.png"'),
  array('id' => '19','pokemon_name' => 'Fletchling','pokemon_type1' => '1','pokemon_type2' => '5','main_color' => '1','accent_color' => '13','sprites' => '"Exported Crops\\19_FLETCHLING.png"'),
  array('id' => '20','pokemon_name' => 'Fletchinder','pokemon_type1' => '2','pokemon_type2' => '5','main_color' => '1','accent_color' => '13','sprites' => '"Exported Crops\\20_FLETCHINDER.png"'),
  array('id' => '21','pokemon_name' => 'Talonflame','pokemon_type1' => '2','pokemon_type2' => '5','main_color' => '1','accent_color' => '13','sprites' => '"Exported Crops\\20_TALONFLAME.png"'),
  array('id' => '22','pokemon_name' => 'Pawmi','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '1','accent_color' => '13','sprites' => '"Exported Crops\\22_PAWMI.png"'),
  array('id' => '23','pokemon_name' => 'Pawmo','pokemon_type1' => '8','pokemon_type2' => '6','main_color' => '1','accent_color' => '13','sprites' => '"Exported Crops\\23_PAWMO.png"'),
  array('id' => '24','pokemon_name' => 'Pawmot','pokemon_type1' => '8','pokemon_type2' => '6','main_color' => '1','accent_color' => '13','sprites' => '"Exported Crops\\24_PAWMOT.png"'),
  array('id' => '25','pokemon_name' => 'Houndour','pokemon_type1' => '17','pokemon_type2' => '2','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\25_HOUNDOUR.png"'),
  array('id' => '26','pokemon_name' => 'Houndoom','pokemon_type1' => '17','pokemon_type2' => '2','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\26_HOUNDOOM.png"'),
  array('id' => '27','pokemon_name' => 'Yungoos','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '6','accent_color' => '10','sprites' => '"Exported Crops\\27_YUNGOOS.png"'),
  array('id' => '28','pokemon_name' => 'Gumshoos','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '6','accent_color' => '10','sprites' => '"Exported Crops\\28_GUMSHOOS.png"'),
  array('id' => '29','pokemon_name' => 'Skwovet','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '1','accent_color' => '13','sprites' => '"Exported Crops\\29_SKWOVET.png"'),
  array('id' => '30','pokemon_name' => 'Greedent','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '13','accent_color' => '1','sprites' => '"Exported Crops\\30_GREEDENT.png"'),
  array('id' => '31','pokemon_name' => 'Sunkern','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\31_SUNKERN.png"'),
  array('id' => '32','pokemon_name' => 'Sunflora','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '3','accent_color' => '4','sprites' => '"Exported Crops\\32_SUNFLORA.png"'),
  array('id' => '33','pokemon_name' => 'Kricketot','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '12','accent_color' => '3','sprites' => '"Exported Crops\\33_KRICKETOT.png"'),
  array('id' => '34','pokemon_name' => 'Kricketune','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '12','accent_color' => '3','sprites' => '"Exported Crops\\34_KRICKETUNE.png"'),
  array('id' => '35','pokemon_name' => 'Scatterbug','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '9','accent_color' => '5','sprites' => '"Exported Crops\\35_SCATTERBUG.png"'),
  array('id' => '36','pokemon_name' => 'Spewpa','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '5','accent_color' => '9','sprites' => '"Exported Crops\\36_SPEWPA.png"'),
  array('id' => '37','pokemon_name' => 'Vivillion','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '9','accent_color' => '5','sprites' => '"Exported Crops\\37_VIVILLON.png"'),
  array('id' => '38','pokemon_name' => 'Combee','pokemon_type1' => '13','pokemon_type2' => '5','main_color' => '12','accent_color' => '5','sprites' => '"Exported Crops\\38_COMBEE.png"'),
  array('id' => '39','pokemon_name' => 'Vespiquen','pokemon_type1' => '13','pokemon_type2' => '5','main_color' => '12','accent_color' => '5','sprites' => '"Exported Crops\\39_VESPIQUEN.png"'),
  array('id' => '40','pokemon_name' => 'Rookidee','pokemon_type1' => '5','pokemon_type2' => '0','main_color' => '3','accent_color' => '5','sprites' => '"Exported Crops\\40_ROOKIDEE.png"'),
  array('id' => '41','pokemon_name' => 'Corvisquire','pokemon_type1' => '5','pokemon_type2' => '0','main_color' => '8','accent_color' => '0','sprites' => '"Exported Crops\\41_CORVISQUIRE.png"'),
  array('id' => '42','pokemon_name' => 'Corviknight','pokemon_type1' => '5','pokemon_type2' => '15','main_color' => '8','accent_color' => '0','sprites' => '"Exported Crops\\42_CORVIKNIGHT.png"'),
  array('id' => '43','pokemon_name' => 'Happiny','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\43_HAPPINY.png"'),
  array('id' => '44','pokemon_name' => 'Chansey','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '13','accent_color' => '4','sprites' => '"Exported Crops\\44_CHANSEY.png"'),
  array('id' => '45','pokemon_name' => 'Blissey','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\45_BLISSEY.png"'),
  array('id' => '46','pokemon_name' => 'Azurill','pokemon_type1' => '1','pokemon_type2' => '18','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\46_AZURILL.png"'),
  array('id' => '47','pokemon_name' => 'Marill','pokemon_type1' => '3','pokemon_type2' => '18','main_color' => '4','accent_color' => '9','sprites' => '"Exported Crops\\47_MARILL.png"'),
  array('id' => '48','pokemon_name' => 'Azumarill','pokemon_type1' => '3','pokemon_type2' => '18','main_color' => '3','accent_color' => '9','sprites' => '"Exported Crops\\48_AZUMARILL.png"'),
  array('id' => '49','pokemon_name' => 'Surskit','pokemon_type1' => '13','pokemon_type2' => '5','main_color' => '5','accent_color' => '3','sprites' => '"Exported Crops\\49_SURSKIT.png"'),
  array('id' => '50','pokemon_name' => 'Masquerain','pokemon_type1' => '13','pokemon_type2' => '5','main_color' => '4','accent_color' => '1','sprites' => '"Exported Crops\\50_MASQUERAIN.png"'),
  array('id' => '51','pokemon_name' => 'Buizel','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\51_BUIZEL.png"'),
  array('id' => '52','pokemon_name' => 'Floatzel','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\52_FLOATZEL.png"'),
  array('id' => '53','pokemon_name' => 'Paldean Wooper','pokemon_type1' => '7','pokemon_type2' => '9','main_color' => '7','accent_color' => '12','sprites' => '"Exported Crops\\53_WOOPER.png"'),
  array('id' => '54','pokemon_name' => 'Clodsire','pokemon_type1' => '7','pokemon_type2' => '9','main_color' => '7','accent_color' => '0','sprites' => '"Exported Crops\\54_CLODSIRE.png"'),
  array('id' => '55','pokemon_name' => 'Psyduck','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '11','accent_color' => '0','sprites' => '"Exported Crops\\55_PSYDUCK.png"'),
  array('id' => '56','pokemon_name' => 'Golduck','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '2','accent_color' => '12','sprites' => '"Exported Crops\\56_GOLDUCK.png"'),
  array('id' => '57','pokemon_name' => 'Chewtle','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '4','accent_color' => '12','sprites' => '"Exported Crops\\57_CHEWTLE.png"'),
  array('id' => '58','pokemon_name' => 'Drednaw','pokemon_type1' => '3','pokemon_type2' => '10','main_color' => '12','accent_color' => '11','sprites' => '"Exported Crops\\58_DREDNAW.png"'),
  array('id' => '59','pokemon_name' => 'Igglybuff','pokemon_type1' => '1','pokemon_type2' => '18','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\59_IGGLYBUFF.png"'),
  array('id' => '60','pokemon_name' => 'Jigglypuff','pokemon_type1' => '1','pokemon_type2' => '18','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\60_JIGGLYPUFF.png"'),
  array('id' => '61','pokemon_name' => 'Wigglytuff','pokemon_type1' => '1','pokemon_type2' => '18','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\61_WIGGLYTUFF"'),
  array('id' => '62','pokemon_name' => 'Ralts','pokemon_type1' => '11','pokemon_type2' => '18','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\62_RALTS.png"'),
  array('id' => '63','pokemon_name' => 'Kirlia','pokemon_type1' => '11','pokemon_type2' => '18','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\63_KIRLIA.png"'),
  array('id' => '64','pokemon_name' => 'Gardevoir','pokemon_type1' => '11','pokemon_type2' => '18','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\64_GARDEVOIR.png"'),
  array('id' => '65','pokemon_name' => 'Gallade','pokemon_type1' => '11','pokemon_type2' => '6','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\65_GALLADE.png"'),
  array('id' => '66','pokemon_name' => 'Drowzee','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\66_DROWZEE.png"'),
  array('id' => '67','pokemon_name' => 'Hypno','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\67_HYPNO.png"'),
  array('id' => '68','pokemon_name' => 'Gastly','pokemon_type1' => '14','pokemon_type2' => '7','main_color' => '2','accent_color' => '7','sprites' => '"Exported Crops\\68_GASTLY.png"'),
  array('id' => '69','pokemon_name' => 'Haunter','pokemon_type1' => '14','pokemon_type2' => '7','main_color' => '7','accent_color' => '2','sprites' => '"Exported Crops\\69_HAUNTER.png"'),
  array('id' => '70','pokemon_name' => 'Gengar','pokemon_type1' => '14','pokemon_type2' => '7','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\70_GENGAR.png"'),
  array('id' => '71','pokemon_name' => 'Tandemaus','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\71_TANDEMAUS.png"'),
  array('id' => '72','pokemon_name' => 'Maushold','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\72_MAUSHOLD.png"'),
  array('id' => '73','pokemon_name' => 'Pichu','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\73_PICHU.png"'),
  array('id' => '74','pokemon_name' => 'Pikachu','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '12','accent_color' => '0','sprites' => '"Exported Crops\\74_PIKACHU.png"'),
  array('id' => '75','pokemon_name' => 'Raichu','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '12','accent_color' => '0','sprites' => '"Exported Crops\\75_RAICHU.png"'),
  array('id' => '76','pokemon_name' => 'Fidough','pokemon_type1' => '18','pokemon_type2' => '0','main_color' => '6','accent_color' => '3','sprites' => '"Exported Crops\\76_FIDOUGH.png"'),
  array('id' => '77','pokemon_name' => 'Dachsbun','pokemon_type1' => '18','pokemon_type2' => '0','main_color' => '6','accent_color' => '0','sprites' => '"Exported Crops\\77_DACHSBUN.png"'),
  array('id' => '78','pokemon_name' => 'Slakoth','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\78_SLAKOTH.png"'),
  array('id' => '79','pokemon_name' => 'Vigoroth','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '13','accent_color' => '12','sprites' => '"Exported Crops\\79_VIGOROTH.png"'),
  array('id' => '80','pokemon_name' => 'Slaking','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '6','accent_color' => '3','sprites' => '"Exported Crops\\80_SLAKING.png"'),
  array('id' => '81','pokemon_name' => 'Bounsweet','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '10','accent_color' => '7','sprites' => '"Exported Crops\\81_BOUNSWEET.png"'),
  array('id' => '82','pokemon_name' => 'Steenee','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '7','accent_color' => '10','sprites' => '"Exported Crops\\82_STEENEE.png"'),
  array('id' => '83','pokemon_name' => 'Tsareena','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '7','accent_color' => '10','sprites' => '"Exported Crops\\83_TSAREENA.png"'),
  array('id' => '84','pokemon_name' => 'Smoliv','pokemon_type1' => '4','pokemon_type2' => '1','main_color' => '4','accent_color' => '5','sprites' => '"Exported Crops\\84_SMOLIV.png"'),
  array('id' => '85','pokemon_name' => 'Dolliv','pokemon_type1' => '4','pokemon_type2' => '1','main_color' => '4','accent_color' => '5','sprites' => '"Exported Crops\\85_DOLLIV.png"'),
  array('id' => '86','pokemon_name' => 'Arboliva','pokemon_type1' => '4','pokemon_type2' => '1','main_color' => '4','accent_color' => '5','sprites' => '"Exported Crops\\86_ARBOLIVA.png"'),
  array('id' => '87','pokemon_name' => 'Bonsly','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '6','accent_color' => '1','sprites' => '"Exported Crops\\87_BONSLY.png"'),
  array('id' => '88','pokemon_name' => 'Sudowoodo','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '4','accent_color' => '1','sprites' => '"Exported Crops\\88_SUDOWOODO.png"'),
  array('id' => '89','pokemon_name' => 'Rockruff','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\89_ROCKRUFF.png"'),
  array('id' => '90','pokemon_name' => 'Lycanroc ','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\90_LYCANROC.png"'),
  array('id' => '91','pokemon_name' => 'Rolycoly','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '11','accent_color' => '5','sprites' => '"Exported Crops\\91_ROLYCOLY.png"'),
  array('id' => '92','pokemon_name' => 'Carkol','pokemon_type1' => '10','pokemon_type2' => '2','main_color' => '11','accent_color' => '5','sprites' => '"Exported Crops\\92_CARKOL.png"'),
  array('id' => '93','pokemon_name' => 'Coalossal','pokemon_type1' => '10','pokemon_type2' => '2','main_color' => '11','accent_color' => '5','sprites' => '"Exported Crops\\93_COALOSSAL.png"'),
  array('id' => '94','pokemon_name' => 'Shinx','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '3','accent_color' => '5','sprites' => '"Exported Crops\\94_SHINX.png"'),
  array('id' => '95','pokemon_name' => 'Luxio','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '3','accent_color' => '5','sprites' => '"Exported Crops\\95_LUXIO.png"'),
  array('id' => '96','pokemon_name' => 'Luxray','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '3','accent_color' => '5','sprites' => '"Exported Crops\\96_LUXRAY.png"'),
  array('id' => '97','pokemon_name' => 'Starly','pokemon_type1' => '1','pokemon_type2' => '5','main_color' => '6','accent_color' => '0','sprites' => '"Exported Crops\\97_STARLY.png"'),
  array('id' => '98','pokemon_name' => 'Staravia','pokemon_type1' => '1','pokemon_type2' => '5','main_color' => '6','accent_color' => '0','sprites' => '"Exported Crops\\98_STARAVIA.png"'),
  array('id' => '99','pokemon_name' => 'Staraptor','pokemon_type1' => '1','pokemon_type2' => '5','main_color' => '6','accent_color' => '0','sprites' => '"Exported Crops\\99_STARAPTOR.png"'),
  array('id' => '100','pokemon_name' => 'Oricorio (Baile)','pokemon_type1' => '2','pokemon_type2' => '5','main_color' => '5','accent_color' => '1','sprites' => '"Exported Crops\\100_1_ORICORIO.png"'),
  array('id' => '101','pokemon_name' => 'Oricorio (Pom-Pom)','pokemon_type1' => '8','pokemon_type2' => '5','main_color' => '3','accent_color' => '9','sprites' => '"Exported Crops\\100_2_ORICORIO.png"'),
  array('id' => '102','pokemon_name' => 'Oricorio (Pa\'u)','pokemon_type1' => '11','pokemon_type2' => '5','main_color' => '10','accent_color' => '3','sprites' => '"Exported Crops\\100_3_ORICORIO.png"'),
  array('id' => '103','pokemon_name' => 'Oricorio (Sensu)','pokemon_type1' => '14','pokemon_type2' => '5','main_color' => '11','accent_color' => '7','sprites' => '"Exported Crops\\100_4_ORICORIO.png"'),
  array('id' => '104','pokemon_name' => 'Mareep','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '10','accent_color' => '2','sprites' => '"Exported Crops\\101_MAREEP.png"'),
  array('id' => '105','pokemon_name' => 'Flaafy','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\102_FLAAFFY.png"'),
  array('id' => '106','pokemon_name' => 'Ampharos','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '10','accent_color' => '2','sprites' => '"Exported Crops\\103_AMPHAROS.png"'),
  array('id' => '107','pokemon_name' => 'Petilil','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\104_PETILIL.png"'),
  array('id' => '108','pokemon_name' => 'Lilligant','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '4','accent_color' => '11','sprites' => '"Exported Crops\\105_LILLIGANT.png"'),
  array('id' => '109','pokemon_name' => 'Shroomish','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '13','accent_color' => '12','sprites' => '"Exported Crops\\106_SHROOMISH.png"'),
  array('id' => '110','pokemon_name' => 'Breloom','pokemon_type1' => '4','pokemon_type2' => '6','main_color' => '13','accent_color' => '12','sprites' => '"Exported Crops\\107_BRELOOM.png"'),
  array('id' => '111','pokemon_name' => 'Applin','pokemon_type1' => '4','pokemon_type2' => '16','main_color' => '4','accent_color' => '13','sprites' => '"Exported Crops\\108_APPLIN.png"'),
  array('id' => '112','pokemon_name' => 'Flapple','pokemon_type1' => '4','pokemon_type2' => '16','main_color' => '4','accent_color' => '13','sprites' => '"Exported Crops\\109_FLAPPLE.png"'),
  array('id' => '113','pokemon_name' => 'Appletun','pokemon_type1' => '4','pokemon_type2' => '16','main_color' => '4','accent_color' => '13','sprites' => '"Exported Crops\\110_APPLETUN.png"'),
  array('id' => '114','pokemon_name' => 'Spoink','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '6','accent_color' => '5','sprites' => '"Exported Crops\\111_SPOINK.png"'),
  array('id' => '115','pokemon_name' => 'Grumpig','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '5','accent_color' => '3','sprites' => '"Exported Crops\\112_GRUMPIG.png"'),
  array('id' => '116','pokemon_name' => 'Squawkabilly','pokemon_type1' => '1','pokemon_type2' => '5','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\113_SQUAWKABILLY.png"'),
  array('id' => '117','pokemon_name' => 'Misdreavus','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '3','accent_color' => '12','sprites' => '"Exported Crops\\114_MISDREAVUS.png"'),
  array('id' => '118','pokemon_name' => 'Mismagius','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '3','accent_color' => '12','sprites' => '"Exported Crops\\115_MISMAGIUS.png"'),
  array('id' => '119','pokemon_name' => 'Makuhita','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '3','accent_color' => '1','sprites' => '"Exported Crops\\116_MAKUHITA.png"'),
  array('id' => '120','pokemon_name' => 'Hariyama','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '13','accent_color' => '1','sprites' => '"Exported Crops\\117_HARIYAMA.png"'),
  array('id' => '121','pokemon_name' => 'Crabrawler','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '7','accent_color' => '1','sprites' => '"Exported Crops\\118_CRABRAWLER.png"'),
  array('id' => '122','pokemon_name' => 'Crabominable','pokemon_type1' => '6','pokemon_type2' => '12','main_color' => '8','accent_color' => '1','sprites' => '"Exported Crops\\119_CRABOMINABLE.png"'),
  array('id' => '123','pokemon_name' => 'Salandit','pokemon_type1' => '7','pokemon_type2' => '2','main_color' => '9','accent_color' => '1','sprites' => '"Exported Crops\\120_SALANDIT.png"'),
  array('id' => '124','pokemon_name' => 'Salazzle','pokemon_type1' => '7','pokemon_type2' => '2','main_color' => '8','accent_color' => '10','sprites' => '"Exported Crops\\121_SALAZZLE.png"'),
  array('id' => '125','pokemon_name' => 'Phanpy','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\122_PHANPY.png"'),
  array('id' => '126','pokemon_name' => 'Donphan','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '4','accent_color' => '12','sprites' => '"Exported Crops\\123_DONPHAN.png"'),
  array('id' => '127','pokemon_name' => 'Cufant','pokemon_type1' => '15','pokemon_type2' => '0','main_color' => '12','accent_color' => '11','sprites' => '"Exported Crops\\124_CUFANT.png"'),
  array('id' => '128','pokemon_name' => 'Copperajah','pokemon_type1' => '15','pokemon_type2' => '0','main_color' => '11','accent_color' => '3','sprites' => '"Exported Crops\\125_COPPERAJAH.png"'),
  array('id' => '129','pokemon_name' => 'Gible','pokemon_type1' => '16','pokemon_type2' => '9','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\126_GIBLE.png"'),
  array('id' => '130','pokemon_name' => 'Gabite','pokemon_type1' => '16','pokemon_type2' => '9','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\127_GABITE.png"'),
  array('id' => '131','pokemon_name' => 'Garchomp','pokemon_type1' => '16','pokemon_type2' => '9','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\128_GARCHOMP.png"'),
  array('id' => '132','pokemon_name' => 'Nacli','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '12','accent_color' => '6','sprites' => '"Exported Crops\\129_NACLI.png"'),
  array('id' => '133','pokemon_name' => 'Naclstack','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '6','accent_color' => '1','sprites' => '"Exported Crops\\130_NACLSTACK.png"'),
  array('id' => '134','pokemon_name' => 'Garganacl','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '6','accent_color' => '5','sprites' => '"Exported Crops\\131_GARGANACL.png"'),
  array('id' => '135','pokemon_name' => 'Wingull','pokemon_type1' => '3','pokemon_type2' => '5','main_color' => '9','accent_color' => '4','sprites' => '"Exported Crops\\132_WINGULL.png"'),
  array('id' => '136','pokemon_name' => 'Pelliper','pokemon_type1' => '3','pokemon_type2' => '5','main_color' => '9','accent_color' => '4','sprites' => '"Exported Crops\\133_PELIPPER.png"'),
  array('id' => '137','pokemon_name' => 'Magikarp','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\134_MAGIKARP.png"'),
  array('id' => '138','pokemon_name' => 'Gyarados','pokemon_type1' => '3','pokemon_type2' => '5','main_color' => '1','accent_color' => '0','sprites' => '"Exported Crops\\135_GYARADOS.png"'),
  array('id' => '139','pokemon_name' => 'Arrokuda','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '5','accent_color' => '1','sprites' => '"Exported Crops\\136_ARROKUDA.png"'),
  array('id' => '140','pokemon_name' => 'Barraskewda','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '5','accent_color' => '1','sprites' => '"Exported Crops\\137_BARRASKEWDA.png"'),
  array('id' => '141','pokemon_name' => 'Basculin','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\138_BASCULIN.png"'),
  array('id' => '142','pokemon_name' => 'Gulpin','pokemon_type1' => '7','pokemon_type2' => '0','main_color' => '2','accent_color' => '12','sprites' => '"Exported Crops\\139_GULPIN.png"'),
  array('id' => '143','pokemon_name' => 'Swalot','pokemon_type1' => '7','pokemon_type2' => '0','main_color' => '2','accent_color' => '12','sprites' => '"Exported Crops\\140_SWALOT.png"'),
  array('id' => '144','pokemon_name' => 'Meowth','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '13','accent_color' => '12','sprites' => '"Exported Crops\\141_MEOWTH.png"'),
  array('id' => '145','pokemon_name' => 'Persian','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\142_PERSIAN.png"'),
  array('id' => '146','pokemon_name' => 'Drifloon','pokemon_type1' => '14','pokemon_type2' => '5','main_color' => '3','accent_color' => '2','sprites' => '"Exported Crops\\143_DRIFLOON.png"'),
  array('id' => '147','pokemon_name' => 'Drifblim','pokemon_type1' => '14','pokemon_type2' => '5','main_color' => '3','accent_color' => '2','sprites' => '"Exported Crops\\144_DRIFBLIM.png"'),
  array('id' => '148','pokemon_name' => 'Flabébé','pokemon_type1' => '18','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\145_FLABEBE.png"'),
  array('id' => '149','pokemon_name' => 'Floette','pokemon_type1' => '18','pokemon_type2' => '0','main_color' => '7','accent_color' => '0','sprites' => '"Exported Crops\\146_FLOETTE.png"'),
  array('id' => '150','pokemon_name' => 'Florges','pokemon_type1' => '18','pokemon_type2' => '0','main_color' => '7','accent_color' => '0','sprites' => '"Exported Crops\\147_FLORGES.png"'),
  array('id' => '151','pokemon_name' => 'Diglett','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '6','accent_color' => '2','sprites' => '"Exported Crops\\148_DIGLETT.png"'),
  array('id' => '152','pokemon_name' => 'Dugtrio','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '6','accent_color' => '2','sprites' => '"Exported Crops\\149_DUGTRIO.png"'),
  array('id' => '153','pokemon_name' => 'Torkoal','pokemon_type1' => '2','pokemon_type2' => '0','main_color' => '3','accent_color' => '6','sprites' => '"Exported Crops\\150_TORKOAL.png"'),
  array('id' => '154','pokemon_name' => 'Numel','pokemon_type1' => '2','pokemon_type2' => '9','main_color' => '13','accent_color' => '2','sprites' => '"Exported Crops\\151_NUMEL.png"'),
  array('id' => '155','pokemon_name' => 'Camerupt','pokemon_type1' => '2','pokemon_type2' => '9','main_color' => '5','accent_color' => '13','sprites' => '"Exported Crops\\152_CAMERUPT.png"'),
  array('id' => '156','pokemon_name' => 'Bronzor','pokemon_type1' => '15','pokemon_type2' => '11','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\153_BRONZOR.png"'),
  array('id' => '157','pokemon_name' => 'Bronzong','pokemon_type1' => '15','pokemon_type2' => '11','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\154_BRONZONG.png"'),
  array('id' => '158','pokemon_name' => 'Axew','pokemon_type1' => '16','pokemon_type2' => '0','main_color' => '4','accent_color' => '2','sprites' => '"Exported Crops\\155_AXEW.png"'),
  array('id' => '159','pokemon_name' => 'Fraxure','pokemon_type1' => '16','pokemon_type2' => '0','main_color' => '5','accent_color' => '1','sprites' => '"Exported Crops\\156_FRAXURE.png"'),
  array('id' => '160','pokemon_name' => 'Haxorus','pokemon_type1' => '16','pokemon_type2' => '0','main_color' => '4','accent_color' => '6','sprites' => '"Exported Crops\\157_HAXORUS.png"'),
  array('id' => '161','pokemon_name' => 'Mankey','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '13','accent_color' => '4','sprites' => '"Exported Crops\\158_MANKEY.png"'),
  array('id' => '162','pokemon_name' => 'Primeape','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '3','accent_color' => '8','sprites' => '"Exported Crops\\159_PRIMEAPE.png"'),
  array('id' => '163','pokemon_name' => 'Annihilape','pokemon_type1' => '6','pokemon_type2' => '14','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\160_ANNIHILAPE.png"'),
  array('id' => '164','pokemon_name' => 'Meditite','pokemon_type1' => '6','pokemon_type2' => '11','main_color' => '10','accent_color' => '12','sprites' => '"Exported Crops\\161_MEDITITE.png"'),
  array('id' => '165','pokemon_name' => 'Medicham','pokemon_type1' => '6','pokemon_type2' => '11','main_color' => '2','accent_color' => '13','sprites' => '"Exported Crops\\162_MEDICHAM.png"'),
  array('id' => '166','pokemon_name' => 'Riolu','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '3','accent_color' => '11','sprites' => '"Exported Crops\\163_RIOLU.png"'),
  array('id' => '167','pokemon_name' => 'Lucario','pokemon_type1' => '6','pokemon_type2' => '15','main_color' => '3','accent_color' => '11','sprites' => '"Exported Crops\\164_LUCARIO.png"'),
  array('id' => '168','pokemon_name' => 'Charcadet','pokemon_type1' => '2','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\165_CHARCADET.png"'),
  array('id' => '169','pokemon_name' => 'Armarouge','pokemon_type1' => '2','pokemon_type2' => '11','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\166_ARMAROUGE.png"'),
  array('id' => '170','pokemon_name' => 'Ceruledge','pokemon_type1' => '2','pokemon_type2' => '14','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\167_CERULEDGE.png"'),
  array('id' => '171','pokemon_name' => 'Barboach','pokemon_type1' => '3','pokemon_type2' => '9','main_color' => '8','accent_color' => '3','sprites' => '"Exported Crops\\168_BARBOACH.png"'),
  array('id' => '172','pokemon_name' => 'Whiscash','pokemon_type1' => '3','pokemon_type2' => '9','main_color' => '2','accent_color' => '12','sprites' => '"Exported Crops\\169_WHISCASH.png"'),
  array('id' => '173','pokemon_name' => 'Tadbulb','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '3','accent_color' => '12','sprites' => '"Exported Crops\\170_TADBULB.png"'),
  array('id' => '174','pokemon_name' => 'Bellibolt','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '3','accent_color' => '12','sprites' => '"Exported Crops\\171_BELLIBOLT.png"'),
  array('id' => '175','pokemon_name' => 'Goomy','pokemon_type1' => '17','pokemon_type2' => '0','main_color' => '3','accent_color' => '12','sprites' => '"Exported Crops\\172_GOOMY.png"'),
  array('id' => '176','pokemon_name' => 'Sliggo','pokemon_type1' => '17','pokemon_type2' => '0','main_color' => '3','accent_color' => '12','sprites' => '"Exported Crops\\173_SLIGGOO.png"'),
  array('id' => '177','pokemon_name' => 'Goodra','pokemon_type1' => '17','pokemon_type2' => '0','main_color' => '3','accent_color' => '12','sprites' => '"Exported Crops\\174_GOODRA.png"'),
  array('id' => '178','pokemon_name' => 'Croagunk','pokemon_type1' => '7','pokemon_type2' => '6','main_color' => '11','accent_color' => '10','sprites' => '"Exported Crops\\175_CROAGUNK.png"'),
  array('id' => '179','pokemon_name' => 'Toxicroak','pokemon_type1' => '7','pokemon_type2' => '6','main_color' => '11','accent_color' => '10','sprites' => '"Exported Crops\\176_TOXICROAK.png"'),
  array('id' => '180','pokemon_name' => 'Wattrel','pokemon_type1' => '8','pokemon_type2' => '5','main_color' => '10','accent_color' => '3','sprites' => '"Exported Crops\\177_WATTREL.png"'),
  array('id' => '181','pokemon_name' => 'Kilowattrel','pokemon_type1' => '8','pokemon_type2' => '5','main_color' => '10','accent_color' => '3','sprites' => '"Exported Crops\\178_KILOWATTREL.png"'),
  array('id' => '182','pokemon_name' => 'Eevee','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '13','accent_color' => '0','sprites' => '"Exported Crops\\179_EEVEE.png"'),
  array('id' => '183','pokemon_name' => 'Vaporeon','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\180_VAPOREON.png"'),
  array('id' => '184','pokemon_name' => 'Jolteon','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\181_JOLTEON.png"'),
  array('id' => '185','pokemon_name' => 'Flareon','pokemon_type1' => '2','pokemon_type2' => '0','main_color' => '6','accent_color' => '13','sprites' => '"Exported Crops\\182_FLAREON.png"'),
  array('id' => '186','pokemon_name' => 'Espeon','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\183_ESPEON.png"'),
  array('id' => '187','pokemon_name' => 'Umbreon','pokemon_type1' => '17','pokemon_type2' => '0','main_color' => '5','accent_color' => '2','sprites' => '"Exported Crops\\184_UMBREON.png"'),
  array('id' => '188','pokemon_name' => 'Leafeon','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\185_LEAFEON.png"'),
  array('id' => '189','pokemon_name' => 'Glaceon','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\186_GLACEON.png"'),
  array('id' => '190','pokemon_name' => 'Sylveon','pokemon_type1' => '18','pokemon_type2' => '0','main_color' => '2','accent_color' => '10','sprites' => '"Exported Crops\\187_SYLVEON.png"'),
  array('id' => '191','pokemon_name' => 'Dunsparce','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '3','accent_color' => '10','sprites' => '"Exported Crops\\188_DUNSPARCE.png"'),
  array('id' => '192','pokemon_name' => 'Dudunsparce','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '3','accent_color' => '10','sprites' => '"Exported Crops\\189_DUDUNSPARCE.png"'),
  array('id' => '193','pokemon_name' => 'Deerling','pokemon_type1' => '1','pokemon_type2' => '4','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\190_DEERLING.png"'),
  array('id' => '194','pokemon_name' => 'Sawsbuck','pokemon_type1' => '1','pokemon_type2' => '4','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\191_SAWSBUCK.png"'),
  array('id' => '195','pokemon_name' => 'Girafarig','pokemon_type1' => '1','pokemon_type2' => '11','main_color' => '3','accent_color' => '2','sprites' => '"Exported Crops\\192_GIRAFARIG.png"'),
  array('id' => '196','pokemon_name' => 'Farigiraf','pokemon_type1' => '1','pokemon_type2' => '11','main_color' => '12','accent_color' => '2','sprites' => '"Exported Crops\\193_FARIGIRAF.png"'),
  array('id' => '197','pokemon_name' => 'Grimer','pokemon_type1' => '7','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\194_GRIMER.png"'),
  array('id' => '198','pokemon_name' => 'Muk','pokemon_type1' => '7','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\195_MUK.png"'),
  array('id' => '199','pokemon_name' => 'Maschiff','pokemon_type1' => '17','pokemon_type2' => '0','main_color' => '7','accent_color' => '5','sprites' => '"Exported Crops\\196_MASCHIFF.png"'),
  array('id' => '200','pokemon_name' => 'Mabosstiff','pokemon_type1' => '17','pokemon_type2' => '0','main_color' => '7','accent_color' => '5','sprites' => '"Exported Crops\\197_MABOSSTIFF.png"'),
  array('id' => '201','pokemon_name' => 'Toxel','pokemon_type1' => '8','pokemon_type2' => '7','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\198_TOXEL.png"'),
  array('id' => '202','pokemon_name' => 'Toxitricity','pokemon_type1' => '8','pokemon_type2' => '7','main_color' => '10','accent_color' => '3','sprites' => '"Exported Crops\\199_TOXTRICITY.png"'),
  array('id' => '203','pokemon_name' => 'Dedenne','pokemon_type1' => '8','pokemon_type2' => '18','main_color' => '6','accent_color' => '3','sprites' => '"Exported Crops\\200_DEDENNE.png"'),
  array('id' => '204','pokemon_name' => 'Pachirisu','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '9','accent_color' => '10','sprites' => '"Exported Crops\\201_PACHIRISU.png"'),
  array('id' => '205','pokemon_name' => 'Shroodle','pokemon_type1' => '7','pokemon_type2' => '1','main_color' => '5','accent_color' => '10','sprites' => '"Exported Crops\\202_SHROODLE.png"'),
  array('id' => '206','pokemon_name' => 'Grafaiai','pokemon_type1' => '7','pokemon_type2' => '1','main_color' => '13','accent_color' => '7','sprites' => '"Exported Crops\\203_GRAFAIAI.png"'),
  array('id' => '207','pokemon_name' => 'Stantler','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '4','accent_color' => '1','sprites' => '"Exported Crops\\204_STANTLER.png"'),
  array('id' => '208','pokemon_name' => 'Foongus','pokemon_type1' => '4','pokemon_type2' => '7','main_color' => '13','accent_color' => '7','sprites' => '"Exported Crops\\205_FOONGUS.png"'),
  array('id' => '209','pokemon_name' => 'Amoongus','pokemon_type1' => '4','pokemon_type2' => '7','main_color' => '13','accent_color' => '7','sprites' => '"Exported Crops\\206_AMOONGUSS.png"'),
  array('id' => '210','pokemon_name' => 'Voltorb','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '2','accent_color' => '9','sprites' => '"Exported Crops\\207_VOLTORB.png"'),
  array('id' => '211','pokemon_name' => 'Electrode','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '2','accent_color' => '9','sprites' => '"Exported Crops\\208_ELECTRODE.png"'),
  array('id' => '212','pokemon_name' => 'Magnemite','pokemon_type1' => '8','pokemon_type2' => '15','main_color' => '13','accent_color' => '6','sprites' => '"Exported Crops\\209_MAGNEMITE.png"'),
  array('id' => '213','pokemon_name' => 'Magneton','pokemon_type1' => '8','pokemon_type2' => '15','main_color' => '13','accent_color' => '6','sprites' => '"Exported Crops\\210_MAGNETON.png"'),
  array('id' => '214','pokemon_name' => 'Magnezone','pokemon_type1' => '8','pokemon_type2' => '15','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\211_MAGNEZONE.png"'),
  array('id' => '215','pokemon_name' => 'Ditto','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\212_DITTO.png"'),
  array('id' => '216','pokemon_name' => 'Growlithe','pokemon_type1' => '2','pokemon_type2' => '0','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\213_GROWLITHE.png"'),
  array('id' => '217','pokemon_name' => 'Arcanine','pokemon_type1' => '2','pokemon_type2' => '0','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\214_ARCANINE.png"'),
  array('id' => '218','pokemon_name' => 'Teddiursa','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\215_TEDDIURSA.png"'),
  array('id' => '219','pokemon_name' => 'Ursaring','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\216_URSARING.png"'),
  array('id' => '220','pokemon_name' => 'Zangoose','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '9','accent_color' => '2','sprites' => '"Exported Crops\\217_ZANGOOSE.png"'),
  array('id' => '221','pokemon_name' => 'Serviper','pokemon_type1' => '7','pokemon_type2' => '0','main_color' => '5','accent_color' => '3','sprites' => '"Exported Crops\\218_SEVIPER.png"'),
  array('id' => '222','pokemon_name' => 'Swablu','pokemon_type1' => '1','pokemon_type2' => '5','main_color' => '3','accent_color' => '9','sprites' => '"Exported Crops\\219_SWABLU.png"'),
  array('id' => '223','pokemon_name' => 'Altaria','pokemon_type1' => '16','pokemon_type2' => '5','main_color' => '3','accent_color' => '9','sprites' => '"Exported Crops\\220_ALTARIA.png"'),
  array('id' => '224','pokemon_name' => 'Skiddo','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '13','accent_color' => '4','sprites' => '"Exported Crops\\221_SKIDDO.png"'),
  array('id' => '225','pokemon_name' => 'Gogoat','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '13','accent_color' => '4','sprites' => '"Exported Crops\\222_GOGOAT.png"'),
  array('id' => '226','pokemon_name' => 'Tauros','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\223_TAUROS.png"'),
  array('id' => '227','pokemon_name' => 'Litleo','pokemon_type1' => '2','pokemon_type2' => '1','main_color' => '6','accent_color' => '1','sprites' => '"Exported Crops\\224_LITLEO.png"'),
  array('id' => '228','pokemon_name' => 'Pyroar','pokemon_type1' => '2','pokemon_type2' => '1','main_color' => '3','accent_color' => '1','sprites' => '"Exported Crops\\225_PYROAR.png"'),
  array('id' => '229','pokemon_name' => 'Stunky','pokemon_type1' => '7','pokemon_type2' => '17','main_color' => '13','accent_color' => '1','sprites' => '"Exported Crops\\226_STUNKY.png"'),
  array('id' => '230','pokemon_name' => 'Skuntank','pokemon_type1' => '7','pokemon_type2' => '17','main_color' => '13','accent_color' => '1','sprites' => '"Exported Crops\\227_SKUNTANK.png"'),
  array('id' => '231','pokemon_name' => 'Zorua','pokemon_type1' => '17','pokemon_type2' => '0','main_color' => '5','accent_color' => '2','sprites' => '"Exported Crops\\228_ZORUA.png"'),
  array('id' => '232','pokemon_name' => 'Zoroark','pokemon_type1' => '17','pokemon_type2' => '0','main_color' => '5','accent_color' => '7','sprites' => '"Exported Crops\\229_ZOROARK.png"'),
  array('id' => '233','pokemon_name' => 'Sneasel','pokemon_type1' => '17','pokemon_type2' => '12','main_color' => '10','accent_color' => '3','sprites' => '"Exported Crops\\230_SNEASEL.png"'),
  array('id' => '234','pokemon_name' => 'Weavile','pokemon_type1' => '17','pokemon_type2' => '12','main_color' => '10','accent_color' => '3','sprites' => '"Exported Crops\\231_WEAVILE.png"'),
  array('id' => '235','pokemon_name' => 'Murkrow','pokemon_type1' => '17','pokemon_type2' => '5','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\232_MURKROW.png"'),
  array('id' => '236','pokemon_name' => 'Honchkrow','pokemon_type1' => '17','pokemon_type2' => '5','main_color' => '10','accent_color' => '9','sprites' => '"Exported Crops\\233_HONCHKROW.png"'),
  array('id' => '237','pokemon_name' => 'Gothita','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\234_GOTHITA.png"'),
  array('id' => '238','pokemon_name' => 'Gothorita','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\235_GOTHORITA.png"'),
  array('id' => '239','pokemon_name' => 'Gothitelle','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\236_GOTHITELLE.png"'),
  array('id' => '240','pokemon_name' => 'Sinistea','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '10','accent_color' => '7','sprites' => '"Exported Crops\\237_SINISTEA.png"'),
  array('id' => '241','pokemon_name' => 'Polteageist','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '10','accent_color' => '7','sprites' => '"Exported Crops\\238_POLTEAGEIST.png"'),
  array('id' => '242','pokemon_name' => 'Mimikyu','pokemon_type1' => '14','pokemon_type2' => '18','main_color' => '8','accent_color' => '0','sprites' => '"Exported Crops\\239_MIMIKYU.png"'),
  array('id' => '243','pokemon_name' => 'Klefki','pokemon_type1' => '15','pokemon_type2' => '18','main_color' => '13','accent_color' => '0','sprites' => '"Exported Crops\\240_KLEFKI.png"'),
  array('id' => '244','pokemon_name' => 'Indeedee','pokemon_type1' => '11','pokemon_type2' => '1','main_color' => '11','accent_color' => '0','sprites' => '"Exported Crops\\241_INDEEDEE.png"'),
  array('id' => '245','pokemon_name' => 'Bramblin','pokemon_type1' => '3','pokemon_type2' => '14','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\242_BRAMBLIN.png"'),
  array('id' => '246','pokemon_name' => 'Brambleghast','pokemon_type1' => '3','pokemon_type2' => '14','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\243_BRAMBLEGHAST.png"'),
  array('id' => '247','pokemon_name' => 'Toedscool','pokemon_type1' => '9','pokemon_type2' => '4','main_color' => '8','accent_color' => '0','sprites' => '"Exported Crops\\244_TOEDSCOOL.png"'),
  array('id' => '248','pokemon_name' => 'Toedscruel','pokemon_type1' => '9','pokemon_type2' => '4','main_color' => '10','accent_color' => '5','sprites' => '"Exported Crops\\245_TOEDSCRUEL.png"'),
  array('id' => '249','pokemon_name' => 'Tropius','pokemon_type1' => '4','pokemon_type2' => '5','main_color' => '4','accent_color' => '6','sprites' => '"Exported Crops\\246_TROPIUS.png"'),
  array('id' => '250','pokemon_name' => 'Fomantis','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '4','accent_color' => '3','sprites' => '"Exported Crops\\247_FOMANTIS.png"'),
  array('id' => '251','pokemon_name' => 'Lurantis','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '4','accent_color' => '3','sprites' => '"Exported Crops\\248_LURANTIS.png"'),
  array('id' => '252','pokemon_name' => 'Klawf','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '2','accent_color' => '5','sprites' => '"Exported Crops\\249_KLAWF.png"'),
  array('id' => '253','pokemon_name' => 'Capsakid','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\250_CAPSAKID.png"'),
  array('id' => '254','pokemon_name' => 'Scovillain','pokemon_type1' => '4','pokemon_type2' => '2','main_color' => '3','accent_color' => '2','sprites' => '"Exported Crops\\251_SCOVILLAIN.png"'),
  array('id' => '255','pokemon_name' => 'Cacnea','pokemon_type1' => '4','pokemon_type2' => '0','main_color' => '12','accent_color' => '6','sprites' => '"Exported Crops\\252_CACNEA.png"'),
  array('id' => '256','pokemon_name' => 'Cacturne','pokemon_type1' => '4','pokemon_type2' => '17','main_color' => '12','accent_color' => '6','sprites' => '"Exported Crops\\253_CACTURNE.png"'),
  array('id' => '257','pokemon_name' => 'Rellor','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '3','accent_color' => '6','sprites' => '"Exported Crops\\254_RELLOR.png"'),
  array('id' => '258','pokemon_name' => 'Rabsca','pokemon_type1' => '13','pokemon_type2' => '11','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\255_RABSCA.png"'),
  array('id' => '259','pokemon_name' => 'Venonat','pokemon_type1' => '13','pokemon_type2' => '7','main_color' => '7','accent_color' => '2','sprites' => '"Exported Crops\\256_VENONAT.png"'),
  array('id' => '260','pokemon_name' => 'Venomoth','pokemon_type1' => '13','pokemon_type2' => '7','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\257_VENOMOTH.png"'),
  array('id' => '261','pokemon_name' => 'Pineco','pokemon_type1' => '13','pokemon_type2' => '0','main_color' => '6','accent_color' => '0','sprites' => '"Exported Crops\\258_PINECO.png"'),
  array('id' => '262','pokemon_name' => 'Forretress','pokemon_type1' => '13','pokemon_type2' => '15','main_color' => '2','accent_color' => '6','sprites' => '"Exported Crops\\259_FORRETRESS.png"'),
  array('id' => '263','pokemon_name' => 'Scyther','pokemon_type1' => '13','pokemon_type2' => '5','main_color' => '4','accent_color' => '1','sprites' => '"Exported Crops\\260_SCYTHER.png"'),
  array('id' => '264','pokemon_name' => 'Scizor','pokemon_type1' => '13','pokemon_type2' => '15','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\261_SCIZOR.png"'),
  array('id' => '265','pokemon_name' => 'Heracross','pokemon_type1' => '13','pokemon_type2' => '6','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\262_HERACROSS.png"'),
  array('id' => '266','pokemon_name' => 'Flittle','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\263_FLITTLE.png"'),
  array('id' => '267','pokemon_name' => 'Espathra','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '5','accent_color' => '7','sprites' => '"Exported Crops\\264_ESPATHRA.png"'),
  array('id' => '268','pokemon_name' => 'Hippopotas','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\265_HIPPOPOTAS.png"'),
  array('id' => '269','pokemon_name' => 'Hippowdon','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\266_HIPPOWDON.png"'),
  array('id' => '270','pokemon_name' => 'Sandile','pokemon_type1' => '9','pokemon_type2' => '17','main_color' => '3','accent_color' => '2','sprites' => '"Exported Crops\\267_SANDILE.png"'),
  array('id' => '271','pokemon_name' => 'Krokorok','pokemon_type1' => '9','pokemon_type2' => '17','main_color' => '6','accent_color' => '3','sprites' => '"Exported Crops\\268_KROKOROK.png"'),
  array('id' => '272','pokemon_name' => 'Krookodile','pokemon_type1' => '9','pokemon_type2' => '17','main_color' => '6','accent_color' => '3','sprites' => '"Exported Crops\\269_KROOKODILE.png"'),
  array('id' => '273','pokemon_name' => 'Silicobra','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '8','accent_color' => '4','sprites' => '"Exported Crops\\270_SILICOBRA.png"'),
  array('id' => '274','pokemon_name' => 'Sandaconda','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '9','accent_color' => '5','sprites' => '"Exported Crops\\271_SANDACONDA.png"'),
  array('id' => '275','pokemon_name' => 'Mudbray','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '12','accent_color' => '5','sprites' => '"Exported Crops\\272_MUDBRAY.png"'),
  array('id' => '276','pokemon_name' => 'Mudsdale','pokemon_type1' => '9','pokemon_type2' => '0','main_color' => '12','accent_color' => '5','sprites' => '"Exported Crops\\273_MUDSDALE.png"'),
  array('id' => '277','pokemon_name' => 'Larvesta','pokemon_type1' => '13','pokemon_type2' => '2','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\274_LARVESTA.png"'),
  array('id' => '278','pokemon_name' => 'Volcarona','pokemon_type1' => '13','pokemon_type2' => '2','main_color' => '12','accent_color' => '7','sprites' => '"Exported Crops\\275_VOLCARONA.png"'),
  array('id' => '279','pokemon_name' => 'Bagon','pokemon_type1' => '16','pokemon_type2' => '0','main_color' => '3','accent_color' => '8','sprites' => '"Exported Crops\\276_BAGON.png"'),
  array('id' => '280','pokemon_name' => 'Shelgon','pokemon_type1' => '16','pokemon_type2' => '0','main_color' => '3','accent_color' => '5','sprites' => '"Exported Crops\\277_SHELGON.png"'),
  array('id' => '281','pokemon_name' => 'Salamence','pokemon_type1' => '16','pokemon_type2' => '5','main_color' => '3','accent_color' => '1','sprites' => '"Exported Crops\\278_SALAMENCE.png"'),
  array('id' => '282','pokemon_name' => 'Tinkatink','pokemon_type1' => '18','pokemon_type2' => '15','main_color' => '14','accent_color' => '12','sprites' => '"Exported Crops\\279_TINKATINK.png"'),
  array('id' => '283','pokemon_name' => 'Tinkaton','pokemon_type1' => '18','pokemon_type2' => '15','main_color' => '14','accent_color' => '12','sprites' => '"Exported Crops\\280_TINKATUFF.png"'),
  array('id' => '284','pokemon_name' => 'Tinkatuff','pokemon_type1' => '18','pokemon_type2' => '15','main_color' => '14','accent_color' => '12','sprites' => '"Exported Crops\\281_TINKATON.png"'),
  array('id' => '285','pokemon_name' => 'Hattena','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\282_HATENNA.png"'),
  array('id' => '286','pokemon_name' => 'Hattrem','pokemon_type1' => '11','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\283_HATTREM.png"'),
  array('id' => '287','pokemon_name' => 'Hatterene','pokemon_type1' => '11','pokemon_type2' => '18','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\284_HATTERENE.png"'),
  array('id' => '288','pokemon_name' => 'Impidimp','pokemon_type1' => '17','pokemon_type2' => '18','main_color' => '11','accent_color' => '9','sprites' => '"Exported Crops\\285_IMPIDIMP.png"'),
  array('id' => '289','pokemon_name' => 'Morgrem','pokemon_type1' => '17','pokemon_type2' => '18','main_color' => '11','accent_color' => '10','sprites' => '"Exported Crops\\286_MORGREM.png"'),
  array('id' => '290','pokemon_name' => 'Grimmsnarl','pokemon_type1' => '17','pokemon_type2' => '18','main_color' => '9','accent_color' => '10','sprites' => '"Exported Crops\\287_GRIMMSNARL.png"'),
  array('id' => '291','pokemon_name' => 'Wiglett','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '3','accent_color' => '2','sprites' => '"Exported Crops\\288_WIGLETT.png"'),
  array('id' => '292','pokemon_name' => 'Wugtrio','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '2','accent_color' => '3','sprites' => '"Exported Crops\\289_WUGTRIO.png"'),
  array('id' => '293','pokemon_name' => 'Bombirdier','pokemon_type1' => '5','pokemon_type2' => '17','main_color' => '13','accent_color' => '0','sprites' => '"Exported Crops\\291_FINIZEN.png"'),
  array('id' => '294','pokemon_name' => 'Finizen','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\292_PALAFIN.png"'),
  array('id' => '295','pokemon_name' => 'Palafin','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\293_VAROOM.png"'),
  array('id' => '296','pokemon_name' => 'Varoom','pokemon_type1' => '15','pokemon_type2' => '7','main_color' => '7','accent_color' => '3','sprites' => '"Exported Crops\\294_REVAVROOM.png"'),
  array('id' => '297','pokemon_name' => 'Revaroom','pokemon_type1' => '15','pokemon_type2' => '7','main_color' => '3','accent_color' => '7','sprites' => '"Exported Crops\\295_BOMBIRDIER.png"'),
  array('id' => '298','pokemon_name' => 'Cyclizar','pokemon_type1' => '16','pokemon_type2' => '1','main_color' => '13','accent_color' => '0','sprites' => '"Exported Crops\\295_CYCLIZAR.png"'),
  array('id' => '299','pokemon_name' => 'Orthworm','pokemon_type1' => '15','pokemon_type2' => '0','main_color' => '2','accent_color' => '9','sprites' => '"Exported Crops\\296_ORTHWORM.png"'),
  array('id' => '300','pokemon_name' => 'Sableye','pokemon_type1' => '17','pokemon_type2' => '14','main_color' => '12','accent_color' => '3','sprites' => '"Exported Crops\\297_SABLEYE.png"'),
  array('id' => '301','pokemon_name' => 'Shuppet','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '11','accent_color' => '0','sprites' => '"Exported Crops\\298_SHUPPET.png"'),
  array('id' => '302','pokemon_name' => 'Banette','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '11','accent_color' => '3','sprites' => '"Exported Crops\\299_BANETTE.png"'),
  array('id' => '303','pokemon_name' => 'Falinks','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '6','accent_color' => '2','sprites' => '"Exported Crops\\300_FALINKS.png"'),
  array('id' => '304','pokemon_name' => 'Hawlucha','pokemon_type1' => '6','pokemon_type2' => '5','main_color' => '7','accent_color' => '1','sprites' => '"Exported Crops\\301_HAWLUCHA.png"'),
  array('id' => '305','pokemon_name' => 'Spiritomb','pokemon_type1' => '14','pokemon_type2' => '17','main_color' => '11','accent_color' => '10','sprites' => '"Exported Crops\\302_SPIRITOMB.png"'),
  array('id' => '306','pokemon_name' => 'Noibat','pokemon_type1' => '5','pokemon_type2' => '16','main_color' => '11','accent_color' => '5','sprites' => '"Exported Crops\\303_NOIBAT.png"'),
  array('id' => '307','pokemon_name' => 'Noivern','pokemon_type1' => '5','pokemon_type2' => '16','main_color' => '4','accent_color' => '5','sprites' => '"Exported Crops\\304_NOIVERN.png"'),
  array('id' => '308','pokemon_name' => 'Dreepy','pokemon_type1' => '16','pokemon_type2' => '14','main_color' => '11','accent_color' => '3','sprites' => '"Exported Crops\\305_DREEPY.png"'),
  array('id' => '309','pokemon_name' => 'Drakloak','pokemon_type1' => '16','pokemon_type2' => '14','main_color' => '11','accent_color' => '3','sprites' => '"Exported Crops\\306_DRAKLOAK.png"'),
  array('id' => '310','pokemon_name' => 'Dragapult','pokemon_type1' => '16','pokemon_type2' => '14','main_color' => '11','accent_color' => '3','sprites' => '"Exported Crops\\307_DRAGAPULT.png"'),
  array('id' => '311','pokemon_name' => 'Glimmet','pokemon_type1' => '10','pokemon_type2' => '7','main_color' => '11','accent_color' => '2','sprites' => '"Exported Crops\\308_GLIMMET.png"'),
  array('id' => '312','pokemon_name' => 'Glimmora','pokemon_type1' => '10','pokemon_type2' => '7','main_color' => '11','accent_color' => '2','sprites' => '"Exported Crops\\309_GLIMMORA.png"'),
  array('id' => '313','pokemon_name' => 'Rotom','pokemon_type1' => '8','pokemon_type2' => '14','main_color' => '1','accent_color' => '12','sprites' => '"Exported Crops\\310_ROTOM.png"'),
  array('id' => '314','pokemon_name' => 'Greavard','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '3','accent_color' => '9','sprites' => '"Exported Crops\\311_GREAVARD.png"'),
  array('id' => '315','pokemon_name' => 'Houndstone','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '3','accent_color' => '9','sprites' => '"Exported Crops\\312_HOUNDSTONE.png"'),
  array('id' => '316','pokemon_name' => 'Oranguru','pokemon_type1' => '1','pokemon_type2' => '11','main_color' => '10','accent_color' => '7','sprites' => '"Exported Crops\\313_ORANGURU.png"'),
  array('id' => '317','pokemon_name' => 'Passimian','pokemon_type1' => '6','pokemon_type2' => '0','main_color' => '2','accent_color' => '12','sprites' => '"Exported Crops\\314_PASSIMIAN.png"'),
  array('id' => '318','pokemon_name' => 'Komala','pokemon_type1' => '1','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\315_KOMALA.png"'),
  array('id' => '319','pokemon_name' => 'Larvitar','pokemon_type1' => '10','pokemon_type2' => '9','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\316_LARVITAR.png"'),
  array('id' => '320','pokemon_name' => 'Pupitar','pokemon_type1' => '10','pokemon_type2' => '9','main_color' => '7','accent_color' => '0','sprites' => '"Exported Crops\\317_PUPITAR.png"'),
  array('id' => '321','pokemon_name' => 'Tyranitar','pokemon_type1' => '10','pokemon_type2' => '17','main_color' => '13','accent_color' => '7','sprites' => '"Exported Crops\\318_TYRANITAR.png"'),
  array('id' => '322','pokemon_name' => 'Stonjourner','pokemon_type1' => '10','pokemon_type2' => '0','main_color' => '5','accent_color' => '6','sprites' => '"Exported Crops\\319_STONJOURNER.png"'),
  array('id' => '323','pokemon_name' => 'Eiscue','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\320_EISCUE.png"'),
  array('id' => '324','pokemon_name' => 'Pinchurchin','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '5','accent_color' => '12','sprites' => '"Exported Crops\\321_PINCURCHIN.png"'),
  array('id' => '325','pokemon_name' => 'Sandyghast','pokemon_type1' => '14','pokemon_type2' => '9','main_color' => '5','accent_color' => '3','sprites' => '"Exported Crops\\322_SANDYGAST.png"'),
  array('id' => '326','pokemon_name' => 'Palossand','pokemon_type1' => '14','pokemon_type2' => '9','main_color' => '5','accent_color' => '3','sprites' => '"Exported Crops\\323_PALOSSAND.png"'),
  array('id' => '327','pokemon_name' => 'Slowpoke','pokemon_type1' => '3','pokemon_type2' => '11','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\324_SLOWPOKE.png"'),
  array('id' => '328','pokemon_name' => 'Slowbro','pokemon_type1' => '3','pokemon_type2' => '11','main_color' => '7','accent_color' => '6','sprites' => '"Exported Crops\\325_SLOWBRO.png"'),
  array('id' => '329','pokemon_name' => 'Slowking','pokemon_type1' => '3','pokemon_type2' => '11','main_color' => '10','accent_color' => '3','sprites' => '"Exported Crops\\326_SLOWKING.png"'),
  array('id' => '330','pokemon_name' => 'Shellos','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '1','accent_color' => '0','sprites' => '"Exported Crops\\327_SHELLOS.png"'),
  array('id' => '331','pokemon_name' => 'Gastrodon','pokemon_type1' => '3','pokemon_type2' => '9','main_color' => '6','accent_color' => '10','sprites' => '"Exported Crops\\328_1_GASTRODON.png"'),
  array('id' => '332','pokemon_name' => 'Shellder','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '12','accent_color' => '0','sprites' => '"Exported Crops\\329_SHELLDER.png"'),
  array('id' => '333','pokemon_name' => 'Cloyster','pokemon_type1' => '3','pokemon_type2' => '12','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\330_CLOYSTER.png"'),
  array('id' => '334','pokemon_name' => 'Qwilfish','pokemon_type1' => '3','pokemon_type2' => '7','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\331_QWILFISH.png"'),
  array('id' => '335','pokemon_name' => 'Luvdisc','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '3','accent_color' => '0','sprites' => '"Exported Crops\\332_LUVDISC.png"'),
  array('id' => '336','pokemon_name' => 'Finneon','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '6','accent_color' => '1','sprites' => '"Exported Crops\\333_FINNEON.png"'),
  array('id' => '337','pokemon_name' => 'Lumineon','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '6','accent_color' => '1','sprites' => '"Exported Crops\\334_LUMINEON.png"'),
  array('id' => '338','pokemon_name' => 'Bruxish','pokemon_type1' => '3','pokemon_type2' => '11','main_color' => '1','accent_color' => '3','sprites' => '"Exported Crops\\335_BRUXISH.png"'),
  array('id' => '339','pokemon_name' => 'Alomomola','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '7','accent_color' => '0','sprites' => '"Exported Crops\\336_ALOMOMOLA.png"'),
  array('id' => '340','pokemon_name' => 'Skrelp','pokemon_type1' => '7','pokemon_type2' => '3','main_color' => '7','accent_color' => '2','sprites' => '"Exported Crops\\337_SKRELP.png"'),
  array('id' => '341','pokemon_name' => 'Dragalge','pokemon_type1' => '7','pokemon_type2' => '16','main_color' => '7','accent_color' => '4','sprites' => '"Exported Crops\\338_DRAGALGE.png"'),
  array('id' => '342','pokemon_name' => 'Clauncher','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '12','accent_color' => '2','sprites' => '"Exported Crops\\339_CLAUNCHER.png"'),
  array('id' => '343','pokemon_name' => 'Clawitzer','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '1','accent_color' => '3','sprites' => '"Exported Crops\\340_CLAWITZER.png"'),
  array('id' => '344','pokemon_name' => 'Tynamo','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\341_TYNAMO.png"'),
  array('id' => '345','pokemon_name' => 'Eelektrik','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '2','accent_color' => '11','sprites' => '"Exported Crops\\342_EELEKTRIK.png"'),
  array('id' => '346','pokemon_name' => 'Eelektross','pokemon_type1' => '8','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\343_EELEKTROSS.png"'),
  array('id' => '347','pokemon_name' => 'Mareanie','pokemon_type1' => '7','pokemon_type2' => '3','main_color' => '10','accent_color' => '1','sprites' => '"Exported Crops\\344_MAREANIE.png"'),
  array('id' => '348','pokemon_name' => 'Toxapex','pokemon_type1' => '7','pokemon_type2' => '3','main_color' => '10','accent_color' => '1','sprites' => '"Exported Crops\\345_TOXAPEX.png"'),
  array('id' => '349','pokemon_name' => 'Flamigo','pokemon_type1' => '5','pokemon_type2' => '6','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\346_DRATINI.png"'),
  array('id' => '350','pokemon_name' => 'Dratini','pokemon_type1' => '16','pokemon_type2' => '0','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\348_DRAGONAIR.png"'),
  array('id' => '351','pokemon_name' => 'Dragonair','pokemon_type1' => '16','pokemon_type2' => '0','main_color' => '4','accent_color' => '0','sprites' => '"Exported Crops\\348_DRAGONITE.png"'),
  array('id' => '352','pokemon_name' => 'Dragonite','pokemon_type1' => '16','pokemon_type2' => '5','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\350_SNOM.png"'),
  array('id' => '353','pokemon_name' => 'Snom','pokemon_type1' => '12','pokemon_type2' => '13','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\351_FROSMOTH.png"'),
  array('id' => '354','pokemon_name' => 'Frosmoth','pokemon_type1' => '12','pokemon_type2' => '13','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\352_SNOVER.png"'),
  array('id' => '355','pokemon_name' => 'Snover','pokemon_type1' => '4','pokemon_type2' => '12','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\353_ABOMASNOW.png"'),
  array('id' => '356','pokemon_name' => 'Abomnasnow','pokemon_type1' => '4','pokemon_type2' => '12','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\354_DELIBIRD.png"'),
  array('id' => '357','pokemon_name' => 'Delibird','pokemon_type1' => '12','pokemon_type2' => '5','main_color' => '7','accent_color' => '0','sprites' => '"Exported Crops\\355_CUBCHOO.png"'),
  array('id' => '358','pokemon_name' => 'Cubchoo','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '2','accent_color' => '0','sprites' => '"Exported Crops\\356_BEARTIC.png"'),
  array('id' => '359','pokemon_name' => 'Beartic','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '2','accent_color' => '3','sprites' => '"Exported Crops\\357_SNORUNT.png"'),
  array('id' => '360','pokemon_name' => 'Snorunt','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '2','accent_color' => '3','sprites' => '"Exported Crops\\358_GLALIE.png"'),
  array('id' => '361','pokemon_name' => 'Glalie','pokemon_type1' => '12','pokemon_type2' => '14','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\359_FROSLASS.png"'),
  array('id' => '362','pokemon_name' => 'Froslass','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\359_FROSLASS.png"'),
  array('id' => '363','pokemon_name' => 'Cryagonal','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '2','accent_color' => '1','sprites' => '"Exported Crops\\360_CRYOGONAL.png"'),
  array('id' => '364','pokemon_name' => 'Cetoddle','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '5','accent_color' => '1','sprites' => '"Exported Crops\\361_CETODDLE.png"'),
  array('id' => '365','pokemon_name' => 'Cetitan','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '5','accent_color' => '1','sprites' => '"Exported Crops\\362_CETITAN.png"'),
  array('id' => '366','pokemon_name' => 'Bergmite','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\363_BERGMITE.png"'),
  array('id' => '367','pokemon_name' => 'Avalugg','pokemon_type1' => '12','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\364_AVALUGG.png"'),
  array('id' => '368','pokemon_name' => 'Rufflet','pokemon_type1' => '1','pokemon_type2' => '5','main_color' => '13','accent_color' => '6','sprites' => '"Exported Crops\\365_RUFFLET.png"'),
  array('id' => '369','pokemon_name' => 'Braviary','pokemon_type1' => '1','pokemon_type2' => '5','main_color' => '2','accent_color' => '5','sprites' => '"Exported Crops\\366_BRAVIARY.png"'),
  array('id' => '370','pokemon_name' => 'Pawniard','pokemon_type1' => '17','pokemon_type2' => '10','main_color' => '2','accent_color' => '5','sprites' => '"Exported Crops\\367_PAWNIARD.png"'),
  array('id' => '371','pokemon_name' => 'Bisharp','pokemon_type1' => '17','pokemon_type2' => '10','main_color' => '2','accent_color' => '5','sprites' => '"Exported Crops\\368_BISHARP.png"'),
  array('id' => '372','pokemon_name' => 'Kingambit','pokemon_type1' => '17','pokemon_type2' => '10','main_color' => '2','accent_color' => '5','sprites' => '"Exported Crops\\369_KINGAMBIT.png"'),
  array('id' => '373','pokemon_name' => 'Deino','pokemon_type1' => '17','pokemon_type2' => '16','main_color' => '4','accent_color' => '5','sprites' => '"Exported Crops\\370_DEINO.png"'),
  array('id' => '374','pokemon_name' => 'Zweilous','pokemon_type1' => '17','pokemon_type2' => '16','main_color' => '4','accent_color' => '6','sprites' => '"Exported Crops\\371_ZWEILOUS.png"'),
  array('id' => '375','pokemon_name' => 'Hydreigon','pokemon_type1' => '17','pokemon_type2' => '16','main_color' => '4','accent_color' => '6','sprites' => '"Exported Crops\\372_HYDREIGON.png"'),
  array('id' => '376','pokemon_name' => 'Veluza','pokemon_type1' => '3','pokemon_type2' => '11','main_color' => '9','accent_color' => '4','sprites' => '"Exported Crops\\373_VELUZA.png"'),
  array('id' => '377','pokemon_name' => 'Dodonzo','pokemon_type1' => '3','pokemon_type2' => '0','main_color' => '9','accent_color' => '3','sprites' => '"Exported Crops\\374_DONDOZO.png"'),
  array('id' => '378','pokemon_name' => 'Tatsugiri','pokemon_type1' => '16','pokemon_type2' => '3','main_color' => '6','accent_color' => '9','sprites' => '"Exported Crops\\375_1_TATSUGIRI.png"'),
  array('id' => '379','pokemon_name' => 'Great Tusk','pokemon_type1' => '9','pokemon_type2' => '6','main_color' => '6','accent_color' => '11','sprites' => '"Exported Crops\\376_GREATTUSK.png"'),
  array('id' => '380','pokemon_name' => 'Scream Tail','pokemon_type1' => '18','pokemon_type2' => '11','main_color' => '10','accent_color' => '0','sprites' => '"Exported Crops\\377_SCREAMTAIL.png"'),
  array('id' => '381','pokemon_name' => 'Brute Bonnet','pokemon_type1' => '4','pokemon_type2' => '17','main_color' => '9','accent_color' => '7','sprites' => '"Exported Crops\\378_BRUTEBONNET.png"'),
  array('id' => '382','pokemon_name' => 'Flutter Mane','pokemon_type1' => '14','pokemon_type2' => '18','main_color' => '4','accent_color' => '1','sprites' => '"Exported Crops\\379_FLUTTERMANE.png"'),
  array('id' => '383','pokemon_name' => 'Slither Wing','pokemon_type1' => '13','pokemon_type2' => '6','main_color' => '3','accent_color' => '12','sprites' => '"Exported Crops\\380_SLITHERWING.png"'),
  array('id' => '384','pokemon_name' => 'Sandy Shocks','pokemon_type1' => '8','pokemon_type2' => '9','main_color' => '3','accent_color' => '5','sprites' => '"Exported Crops\\381_SANDYSHOCKS.png"'),
  array('id' => '385','pokemon_name' => 'Iron Treads','pokemon_type1' => '9','pokemon_type2' => '15','main_color' => '8','accent_color' => '1','sprites' => '"Exported Crops\\382_IRONTREADS.png"'),
  array('id' => '386','pokemon_name' => 'Iron Bundle','pokemon_type1' => '12','pokemon_type2' => '3','main_color' => '8','accent_color' => '2','sprites' => '"Exported Crops\\383_IRONBUNDLE.png"'),
  array('id' => '387','pokemon_name' => 'Iron Hands','pokemon_type1' => '6','pokemon_type2' => '8','main_color' => '8','accent_color' => '3','sprites' => '"Exported Crops\\384_IRONHANDS.png"'),
  array('id' => '388','pokemon_name' => 'Iron Jugulis','pokemon_type1' => '17','pokemon_type2' => '5','main_color' => '8','accent_color' => '10','sprites' => '"Exported Crops\\385_IRONJUGULIS.png"'),
  array('id' => '389','pokemon_name' => 'Iron Moth','pokemon_type1' => '2','pokemon_type2' => '7','main_color' => '8','accent_color' => '12','sprites' => '"Exported Crops\\386_IRONMOTH.png"'),
  array('id' => '390','pokemon_name' => 'Iron Thorns','pokemon_type1' => '10','pokemon_type2' => '8','main_color' => '8','accent_color' => '4','sprites' => '"Exported Crops\\387_IRONTHORNS.png"'),
  array('id' => '391','pokemon_name' => 'Frigibax','pokemon_type1' => '16','pokemon_type2' => '12','main_color' => '11','accent_color' => '3','sprites' => '"Exported Crops\\388_FRIGIBAX.png"'),
  array('id' => '392','pokemon_name' => 'Arctibax','pokemon_type1' => '16','pokemon_type2' => '12','main_color' => '11','accent_color' => '10','sprites' => '"Exported Crops\\389_ARCTIBAX.png"'),
  array('id' => '393','pokemon_name' => 'Baxcalibur','pokemon_type1' => '16','pokemon_type2' => '12','main_color' => '11','accent_color' => '10','sprites' => '"Exported Crops\\390_BAXCALIBUR.png"'),
  array('id' => '394','pokemon_name' => 'Gimmighoul','pokemon_type1' => '14','pokemon_type2' => '0','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\391_GIMMIGHOUL.png"'),
  array('id' => '395','pokemon_name' => 'Gholdengo','pokemon_type1' => '15','pokemon_type2' => '14','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\392_GHOLDENGO.png"'),
  array('id' => '396','pokemon_name' => 'Wo-Chien','pokemon_type1' => '17','pokemon_type2' => '4','main_color' => '6','accent_color' => '1','sprites' => '"Exported Crops\\393_WO-CHIEN.png"'),
  array('id' => '397','pokemon_name' => 'Chien-Pao','pokemon_type1' => '17','pokemon_type2' => '12','main_color' => '5','accent_color' => '2','sprites' => '"Exported Crops\\394_CHIEN-PAOpng"'),
  array('id' => '398','pokemon_name' => 'Ting-Lu','pokemon_type1' => '17','pokemon_type2' => '9','main_color' => '14','accent_color' => '0','sprites' => '"Exported Crops\\395_TING-LU.png"'),
  array('id' => '399','pokemon_name' => 'Chi-Yu','pokemon_type1' => '17','pokemon_type2' => '2','main_color' => '2','accent_color' => '5','sprites' => '"Exported Crops\\396_CHI-YU.png"'),
  array('id' => '400','pokemon_name' => 'Roaring Moon','pokemon_type1' => '16','pokemon_type2' => '17','main_color' => '11','accent_color' => '1','sprites' => '"Exported Crops\\397_ROARINGMOON.png"'),
  array('id' => '401','pokemon_name' => 'Iron Valiant','pokemon_type1' => '18','pokemon_type2' => '6','main_color' => '8','accent_color' => '10','sprites' => '"Exported Crops\\398_IRONVALIANT.png"'),
  array('id' => '402','pokemon_name' => 'Koraidon','pokemon_type1' => '6','pokemon_type2' => '16','main_color' => '5','accent_color' => '1','sprites' => '"Exported Crops\\399_KORAIDON.png"'),
  array('id' => '403','pokemon_name' => 'Miraidon','pokemon_type1' => '8','pokemon_type2' => '16','main_color' => '8','accent_color' => '7','sprites' => '"Exported Crops\\400_MIRAIDON.png"')
);

/* `shiny_pokemon`.`pokemon_names` */
$pokemon_names = array(
  array('id' => '353','name' => 'Abomnasnow'),
  array('id' => '336','name' => 'Alomomola'),
  array('id' => '220','name' => 'Altaria'),
  array('id' => '206','name' => 'Amoongus'),
  array('id' => '103','name' => 'Ampharos'),
  array('id' => '160','name' => 'Annihilape'),
  array('id' => '110','name' => 'Appletun'),
  array('id' => '108','name' => 'Applin'),
  array('id' => '86','name' => 'Arboliva'),
  array('id' => '214','name' => 'Arcanine'),
  array('id' => '389','name' => 'Arctibax'),
  array('id' => '166','name' => 'Armarouge'),
  array('id' => '136','name' => 'Arrokuda'),
  array('id' => '364','name' => 'Avalugg'),
  array('id' => '155','name' => 'Axew'),
  array('id' => '48','name' => 'Azumarill'),
  array('id' => '46','name' => 'Azurill'),
  array('id' => '276','name' => 'Bagon'),
  array('id' => '299','name' => 'Banette'),
  array('id' => '168','name' => 'Barboach'),
  array('id' => '137','name' => 'Barraskewda'),
  array('id' => '138','name' => 'Basculin'),
  array('id' => '390','name' => 'Baxcalibur'),
  array('id' => '356','name' => 'Beartic'),
  array('id' => '171','name' => 'Bellibolt'),
  array('id' => '363','name' => 'Bergmite'),
  array('id' => '368','name' => 'Bisharp'),
  array('id' => '45','name' => 'Blissey'),
  array('id' => '290','name' => 'Bombirdier'),
  array('id' => '87','name' => 'Bonsly'),
  array('id' => '81','name' => 'Bounsweet'),
  array('id' => '243','name' => 'Brambleghast'),
  array('id' => '242','name' => 'Bramblin'),
  array('id' => '366','name' => 'Braviary'),
  array('id' => '107','name' => 'Breloom'),
  array('id' => '154','name' => 'Bronzong'),
  array('id' => '153','name' => 'Bronzor'),
  array('id' => '378','name' => 'Brute Bonnet'),
  array('id' => '335','name' => 'Bruxish'),
  array('id' => '51','name' => 'Buizel'),
  array('id' => '252','name' => 'Cacnea'),
  array('id' => '253','name' => 'Cacturne'),
  array('id' => '152','name' => 'Camerupt'),
  array('id' => '250','name' => 'Capsakid'),
  array('id' => '92','name' => 'Carkol'),
  array('id' => '167','name' => 'Ceruledge'),
  array('id' => '362','name' => 'Cetitan'),
  array('id' => '361','name' => 'Cetoddle'),
  array('id' => '44','name' => 'Chansey'),
  array('id' => '165','name' => 'Charcadet'),
  array('id' => '57','name' => 'Chewtle'),
  array('id' => '396','name' => 'Chi-Yu'),
  array('id' => '394','name' => 'Chien-Pao'),
  array('id' => '339','name' => 'Clauncher'),
  array('id' => '340','name' => 'Clawitzer'),
  array('id' => '54','name' => 'Clodsire'),
  array('id' => '330','name' => 'Cloyster'),
  array('id' => '93','name' => 'Coalossal'),
  array('id' => '38','name' => 'Combee'),
  array('id' => '125','name' => 'Copperajah'),
  array('id' => '42','name' => 'Corviknight'),
  array('id' => '41','name' => 'Corvisquire'),
  array('id' => '119','name' => 'Crabominable'),
  array('id' => '118','name' => 'Crabrawler'),
  array('id' => '175','name' => 'Croagunk'),
  array('id' => '5','name' => 'Crocalor'),
  array('id' => '360','name' => 'Cryagonal'),
  array('id' => '355','name' => 'Cubchoo'),
  array('id' => '124','name' => 'Cufant'),
  array('id' => '295','name' => 'Cyclizar'),
  array('id' => '77','name' => 'Dachsbun'),
  array('id' => '200','name' => 'Dedenne'),
  array('id' => '190','name' => 'Deerling'),
  array('id' => '370','name' => 'Deino'),
  array('id' => '354','name' => 'Delibird'),
  array('id' => '148','name' => 'Diglett'),
  array('id' => '212','name' => 'Ditto'),
  array('id' => '374','name' => 'Dodonzo'),
  array('id' => '85','name' => 'Dolliv'),
  array('id' => '123','name' => 'Donphan'),
  array('id' => '338','name' => 'Dragalge'),
  array('id' => '307','name' => 'Dragapult'),
  array('id' => '348','name' => 'Dragonair'),
  array('id' => '349','name' => 'Dragonite'),
  array('id' => '306','name' => 'Drakloak'),
  array('id' => '347','name' => 'Dratini'),
  array('id' => '58','name' => 'Drednaw'),
  array('id' => '305','name' => 'Dreepy'),
  array('id' => '144','name' => 'Drifblim'),
  array('id' => '143','name' => 'Drifloon'),
  array('id' => '66','name' => 'Drowzee'),
  array('id' => '189','name' => 'Dudunsparce'),
  array('id' => '149','name' => 'Dugtrio'),
  array('id' => '188','name' => 'Dunsparce'),
  array('id' => '342','name' => 'Eelektrik'),
  array('id' => '343','name' => 'Eelektross'),
  array('id' => '179','name' => 'Eevee'),
  array('id' => '320','name' => 'Eiscue'),
  array('id' => '208','name' => 'Electrode'),
  array('id' => '264','name' => 'Espathra'),
  array('id' => '183','name' => 'Espeon'),
  array('id' => '300','name' => 'Falinks'),
  array('id' => '193','name' => 'Farigiraf'),
  array('id' => '76','name' => 'Fidough'),
  array('id' => '291','name' => 'Finizen'),
  array('id' => '333','name' => 'Finneon'),
  array('id' => '102','name' => 'Flaafy'),
  array('id' => '145','name' => 'Flabébé'),
  array('id' => '346','name' => 'Flamigo'),
  array('id' => '109','name' => 'Flapple'),
  array('id' => '182','name' => 'Flareon'),
  array('id' => '20','name' => 'Fletchinder'),
  array('id' => '19','name' => 'Fletchling'),
  array('id' => '263','name' => 'Flittle'),
  array('id' => '52','name' => 'Floatzel'),
  array('id' => '146','name' => 'Floette'),
  array('id' => '2','name' => 'Floragato'),
  array('id' => '147','name' => 'Florges'),
  array('id' => '379','name' => 'Flutter Mane'),
  array('id' => '247','name' => 'Fomantis'),
  array('id' => '205','name' => 'Foongus'),
  array('id' => '259','name' => 'Forretress'),
  array('id' => '156','name' => 'Fraxure'),
  array('id' => '388','name' => 'Frigibax'),
  array('id' => '359','name' => 'Froslass'),
  array('id' => '351','name' => 'Frosmoth'),
  array('id' => '4','name' => 'Fuecoco'),
  array('id' => '127','name' => 'Gabite'),
  array('id' => '65','name' => 'Gallade'),
  array('id' => '128','name' => 'Garchomp'),
  array('id' => '64','name' => 'Gardevoir'),
  array('id' => '131','name' => 'Garganacl'),
  array('id' => '68','name' => 'Gastly'),
  array('id' => '328','name' => 'Gastrodon'),
  array('id' => '70','name' => 'Gengar'),
  array('id' => '392','name' => 'Gholdengo'),
  array('id' => '126','name' => 'Gible'),
  array('id' => '391','name' => 'Gimmighoul'),
  array('id' => '192','name' => 'Girafarig'),
  array('id' => '186','name' => 'Glaceon'),
  array('id' => '358','name' => 'Glalie'),
  array('id' => '308','name' => 'Glimmet'),
  array('id' => '309','name' => 'Glimmora'),
  array('id' => '222','name' => 'Gogoat'),
  array('id' => '56','name' => 'Golduck'),
  array('id' => '174','name' => 'Goodra'),
  array('id' => '172','name' => 'Goomy'),
  array('id' => '234','name' => 'Gothita'),
  array('id' => '236','name' => 'Gothitelle'),
  array('id' => '235','name' => 'Gothorita'),
  array('id' => '203','name' => 'Grafaiai'),
  array('id' => '376','name' => 'Great Tusk'),
  array('id' => '311','name' => 'Greavard'),
  array('id' => '30','name' => 'Greedent'),
  array('id' => '194','name' => 'Grimer'),
  array('id' => '287','name' => 'Grimmsnarl'),
  array('id' => '213','name' => 'Growlithe'),
  array('id' => '112','name' => 'Grumpig'),
  array('id' => '139','name' => 'Gulpin'),
  array('id' => '28','name' => 'Gumshoos'),
  array('id' => '135','name' => 'Gyarados'),
  array('id' => '43','name' => 'Happiny'),
  array('id' => '117','name' => 'Hariyama'),
  array('id' => '282','name' => 'Hattena'),
  array('id' => '284','name' => 'Hatterene'),
  array('id' => '283','name' => 'Hattrem'),
  array('id' => '69','name' => 'Haunter'),
  array('id' => '301','name' => 'Hawlucha'),
  array('id' => '157','name' => 'Haxorus'),
  array('id' => '262','name' => 'Heracross'),
  array('id' => '265','name' => 'Hippopotas'),
  array('id' => '266','name' => 'Hippowdon'),
  array('id' => '233','name' => 'Honchkrow'),
  array('id' => '16','name' => 'Hoppip'),
  array('id' => '26','name' => 'Houndoom'),
  array('id' => '25','name' => 'Houndour'),
  array('id' => '312','name' => 'Houndstone'),
  array('id' => '372','name' => 'Hydreigon'),
  array('id' => '67','name' => 'Hypno'),
  array('id' => '59','name' => 'Igglybuff'),
  array('id' => '285','name' => 'Impidimp'),
  array('id' => '241','name' => 'Indeedee'),
  array('id' => '383','name' => 'Iron Bundle'),
  array('id' => '384','name' => 'Iron Hands'),
  array('id' => '385','name' => 'Iron Jugulis'),
  array('id' => '386','name' => 'Iron Moth'),
  array('id' => '387','name' => 'Iron Thorns'),
  array('id' => '382','name' => 'Iron Treads'),
  array('id' => '398','name' => 'Iron Valiant'),
  array('id' => '60','name' => 'Jigglypuff'),
  array('id' => '181','name' => 'Jolteon'),
  array('id' => '18','name' => 'Jumpluff'),
  array('id' => '178','name' => 'Kilowattrel'),
  array('id' => '369','name' => 'Kingambit'),
  array('id' => '63','name' => 'Kirlia'),
  array('id' => '249','name' => 'Klawf'),
  array('id' => '240','name' => 'Klefki'),
  array('id' => '315','name' => 'Komala'),
  array('id' => '399','name' => 'Koraidon'),
  array('id' => '33','name' => 'Kricketot'),
  array('id' => '34','name' => 'Kricketune'),
  array('id' => '268','name' => 'Krokorok'),
  array('id' => '269','name' => 'Krookodile'),
  array('id' => '274','name' => 'Larvesta'),
  array('id' => '316','name' => 'Larvitar'),
  array('id' => '185','name' => 'Leafeon'),
  array('id' => '10','name' => 'Lechonk'),
  array('id' => '105','name' => 'Lilligant'),
  array('id' => '224','name' => 'Litleo'),
  array('id' => '15','name' => 'Lokix'),
  array('id' => '164','name' => 'Lucario'),
  array('id' => '334','name' => 'Lumineon'),
  array('id' => '248','name' => 'Lurantis'),
  array('id' => '332','name' => 'Luvdisc'),
  array('id' => '95','name' => 'Luxio'),
  array('id' => '96','name' => 'Luxray'),
  array('id' => '90','name' => 'Lycanroc'),
  array('id' => '197','name' => 'Mabosstiff'),
  array('id' => '134','name' => 'Magikarp'),
  array('id' => '209','name' => 'Magnemite'),
  array('id' => '210','name' => 'Magneton'),
  array('id' => '211','name' => 'Magnezone'),
  array('id' => '116','name' => 'Makuhita'),
  array('id' => '158','name' => 'Mankey'),
  array('id' => '344','name' => 'Mareanie'),
  array('id' => '101','name' => 'Mareep'),
  array('id' => '47','name' => 'Marill'),
  array('id' => '196','name' => 'Maschiff'),
  array('id' => '50','name' => 'Masquerain'),
  array('id' => '72','name' => 'Maushold'),
  array('id' => '162','name' => 'Medicham'),
  array('id' => '161','name' => 'Meditite'),
  array('id' => '3','name' => 'Meowscarada'),
  array('id' => '141','name' => 'Meowth'),
  array('id' => '239','name' => 'Mimikyu'),
  array('id' => '400','name' => 'Miraidon'),
  array('id' => '114','name' => 'Misdreavus'),
  array('id' => '115','name' => 'Mismagius'),
  array('id' => '286','name' => 'Morgrem'),
  array('id' => '272','name' => 'Mudbray'),
  array('id' => '273','name' => 'Mudsdale'),
  array('id' => '195','name' => 'Muk'),
  array('id' => '232','name' => 'Murkrow'),
  array('id' => '129','name' => 'Nacli'),
  array('id' => '130','name' => 'Naclstack'),
  array('id' => '303','name' => 'Noibat'),
  array('id' => '304','name' => 'Noivern'),
  array('id' => '151','name' => 'Numel'),
  array('id' => '14','name' => 'Nymble'),
  array('id' => '11','name' => 'Oinkologne'),
  array('id' => '100','name' => 'Oricorio'),
  array('id' => '296','name' => 'Orthworm'),
  array('id' => '201','name' => 'Pachirisu'),
  array('id' => '292','name' => 'Palafin'),
  array('id' => '53','name' => 'Paldean Wooper'),
  array('id' => '323','name' => 'Palossand'),
  array('id' => '314','name' => 'Passimian'),
  array('id' => '22','name' => 'Pawmi'),
  array('id' => '23','name' => 'Pawmo'),
  array('id' => '24','name' => 'Pawmot'),
  array('id' => '367','name' => 'Pawniard'),
  array('id' => '133','name' => 'Pelliper'),
  array('id' => '142','name' => 'Persian'),
  array('id' => '104','name' => 'Petilil'),
  array('id' => '122','name' => 'Phanpy'),
  array('id' => '73','name' => 'Pichu'),
  array('id' => '74','name' => 'Pikachu'),
  array('id' => '321','name' => 'Pinchurchin'),
  array('id' => '258','name' => 'Pineco'),
  array('id' => '238','name' => 'Polteageist'),
  array('id' => '313','name' => 'Ponguru'),
  array('id' => '159','name' => 'Primeape'),
  array('id' => '55','name' => 'Psyduck'),
  array('id' => '317','name' => 'Pupitar'),
  array('id' => '225','name' => 'Pyroar'),
  array('id' => '9','name' => 'Quaquaval'),
  array('id' => '7','name' => 'Quaxly'),
  array('id' => '8','name' => 'Quaxwell'),
  array('id' => '331','name' => 'Qwilfish'),
  array('id' => '255','name' => 'Rabsca'),
  array('id' => '75','name' => 'Raichu'),
  array('id' => '62','name' => 'Ralts'),
  array('id' => '254','name' => 'Rellor'),
  array('id' => '294','name' => 'Revaroom'),
  array('id' => '163','name' => 'Riolu'),
  array('id' => '397','name' => 'Roaring Moon'),
  array('id' => '89','name' => 'Rockruff'),
  array('id' => '91','name' => 'Rolycoly'),
  array('id' => '40','name' => 'Rookidee'),
  array('id' => '310','name' => 'Rotom'),
  array('id' => '365','name' => 'Rufflet'),
  array('id' => '297','name' => 'Sableye'),
  array('id' => '278','name' => 'Salamence'),
  array('id' => '120','name' => 'Salandit'),
  array('id' => '121','name' => 'Salazzle'),
  array('id' => '271','name' => 'Sandaconda'),
  array('id' => '267','name' => 'Sandile'),
  array('id' => '381','name' => 'Sandy Shocks'),
  array('id' => '322','name' => 'Sandyghast'),
  array('id' => '191','name' => 'Sawsbuck'),
  array('id' => '35','name' => 'Scatterbug'),
  array('id' => '261','name' => 'Scizor'),
  array('id' => '251','name' => 'Scovillain'),
  array('id' => '377','name' => 'Scream Tail'),
  array('id' => '260','name' => 'Scyther'),
  array('id' => '218','name' => 'Serviper'),
  array('id' => '277','name' => 'Shelgon'),
  array('id' => '329','name' => 'Shellder'),
  array('id' => '327','name' => 'Shellos'),
  array('id' => '94','name' => 'Shinx'),
  array('id' => '202','name' => 'Shroodle'),
  array('id' => '106','name' => 'Shroomish'),
  array('id' => '298','name' => 'Shuppet'),
  array('id' => '270','name' => 'Silicobra'),
  array('id' => '237','name' => 'Sinistea'),
  array('id' => '6','name' => 'Skeledirge'),
  array('id' => '221','name' => 'Skiddo'),
  array('id' => '17','name' => 'Skiploom'),
  array('id' => '337','name' => 'Skrelp'),
  array('id' => '227','name' => 'Skuntank'),
  array('id' => '29','name' => 'Skwovet'),
  array('id' => '80','name' => 'Slaking'),
  array('id' => '78','name' => 'Slakoth'),
  array('id' => '173','name' => 'Sliggo'),
  array('id' => '380','name' => 'Slither Wing'),
  array('id' => '325','name' => 'Slowbro'),
  array('id' => '326','name' => 'Slowking'),
  array('id' => '324','name' => 'Slowpoke'),
  array('id' => '84','name' => 'Smoliv'),
  array('id' => '230','name' => 'Sneasel'),
  array('id' => '350','name' => 'Snom'),
  array('id' => '357','name' => 'Snorunt'),
  array('id' => '352','name' => 'Snover'),
  array('id' => '36','name' => 'Spewpa'),
  array('id' => '13','name' => 'Spidops'),
  array('id' => '302','name' => 'Spiritomb'),
  array('id' => '111','name' => 'Spoink'),
  array('id' => '1','name' => 'Sprigatito'),
  array('id' => '113','name' => 'Squawkabilly'),
  array('id' => '204','name' => 'Stantler'),
  array('id' => '99','name' => 'Staraptor'),
  array('id' => '98','name' => 'Staravia'),
  array('id' => '97','name' => 'Starly'),
  array('id' => '82','name' => 'Steenee'),
  array('id' => '319','name' => 'Stonjourner'),
  array('id' => '226','name' => 'Stunky'),
  array('id' => '88','name' => 'Sudowoodo'),
  array('id' => '32','name' => 'Sunflora'),
  array('id' => '31','name' => 'Sunkern'),
  array('id' => '49','name' => 'Surskit'),
  array('id' => '219','name' => 'Swablu'),
  array('id' => '140','name' => 'Swalot'),
  array('id' => '187','name' => 'Sylveon'),
  array('id' => '170','name' => 'Tadbulb'),
  array('id' => '21','name' => 'Talonflame'),
  array('id' => '71','name' => 'Tandemaus'),
  array('id' => '12','name' => 'Tarountula'),
  array('id' => '375','name' => 'Tatsugiri'),
  array('id' => '223','name' => 'Tauros'),
  array('id' => '215','name' => 'Teddiursa'),
  array('id' => '395','name' => 'Ting-Lu'),
  array('id' => '279','name' => 'Tinkatink'),
  array('id' => '280','name' => 'Tinkaton'),
  array('id' => '281','name' => 'Tinkatuff'),
  array('id' => '244','name' => 'Toedscool'),
  array('id' => '245','name' => 'Toedscruel'),
  array('id' => '150','name' => 'Torkoal'),
  array('id' => '345','name' => 'Toxapex'),
  array('id' => '198','name' => 'Toxel'),
  array('id' => '176','name' => 'Toxicroak'),
  array('id' => '199','name' => 'Toxitricity'),
  array('id' => '246','name' => 'Tropius'),
  array('id' => '83','name' => 'Tsareena'),
  array('id' => '341','name' => 'Tynamo'),
  array('id' => '318','name' => 'Tyranitar'),
  array('id' => '184','name' => 'Umbreon'),
  array('id' => '216','name' => 'Ursaring'),
  array('id' => '180','name' => 'Vaporeon'),
  array('id' => '293','name' => 'Varoom'),
  array('id' => '373','name' => 'Veluza'),
  array('id' => '257','name' => 'Venomoth'),
  array('id' => '256','name' => 'Venonat'),
  array('id' => '39','name' => 'Vespiquen'),
  array('id' => '79','name' => 'Vigoroth'),
  array('id' => '37','name' => 'Vivillion'),
  array('id' => '275','name' => 'Volcarona'),
  array('id' => '207','name' => 'Voltorb'),
  array('id' => '177','name' => 'Wattrel'),
  array('id' => '231','name' => 'Weavile'),
  array('id' => '169','name' => 'Whiscash'),
  array('id' => '61','name' => 'Wigglytuff'),
  array('id' => '288','name' => 'Wiglett'),
  array('id' => '132','name' => 'Wingull'),
  array('id' => '393','name' => 'Wo-Chien'),
  array('id' => '289','name' => 'Wugtrio'),
  array('id' => '27','name' => 'Yungoos'),
  array('id' => '217','name' => 'Zangoose'),
  array('id' => '229','name' => 'Zoroark'),
  array('id' => '228','name' => 'Zorua'),
  array('id' => '371','name' => 'Zweilous')
);

/* `shiny_pokemon`.`type` */
$type = array(
  array('id' => '1','name' => 'Normal','image' => '"Types\\normal.png"'),
  array('id' => '2','name' => 'Fire','image' => '"Types\\fire.png"'),
  array('id' => '3','name' => 'Water','image' => '"Types\\water.png"'),
  array('id' => '4','name' => 'Grass','image' => '"Types\\grass.png"'),
  array('id' => '5','name' => 'Flying','image' => '"Types\\flying.png"'),
  array('id' => '6','name' => 'Fighting','image' => '"Types\\fighting.png"'),
  array('id' => '7','name' => 'Poison','image' => '"Types\\poison.png"'),
  array('id' => '8','name' => 'Electric','image' => '"Types\\electric.png"'),
  array('id' => '9','name' => 'Ground','image' => '"Types\\ground.png"'),
  array('id' => '10','name' => 'Rock','image' => '"Types\\rock.png"'),
  array('id' => '11','name' => 'Psychic','image' => '"Types\\psychic.png"'),
  array('id' => '12','name' => 'Ice','image' => '"Types\\ice.png"'),
  array('id' => '13','name' => 'Bug','image' => '"Types\\bug.png"'),
  array('id' => '14','name' => 'Ghost','image' => '"Types\\ghost.png"'),
  array('id' => '15','name' => 'Steel','image' => '"Types\\steel.png"'),
  array('id' => '16','name' => 'Dragon','image' => '"Types\\dragon.png"'),
  array('id' => '17','name' => 'Dark','image' => '"Types\\dark.png"'),
  array('id' => '18','name' => 'Fairy','image' => '"Types\\fairy.png"')
);
